config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root to: 'pages#index'
end

app/models/contact.rb
class Contact
  attr_accessor :name, :email, :message

  def initialize(name, email, message)
    @name = name
    @email = email
    @message = message
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
# Contacts Controller
class ContactsController < ApplicationController
  def new
  end

  def create
    pp params
    @contact = Contact.new(params["contact"]["name"], params["contact"]["email"], params["contact"]["message"])
    if @contact
      UserMailer.ask_email(@contact).deliver
      flash[:notice] = 'Zpráva odeslána!'
      redirect_to controller: 'contacts', action: 'new'
    else
      flash[:notice] = 'Zprávu se nepodařilo odeslat!'
      render :new
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

    act = File.join(Rails.root, 'app', 'views', 'pages', 'actually.html.erb')
    act = File.open(act)
    @html_act = Nokogiri::HTML(act, nil, 'utf-8')
    act.close

    info = File.join(Rails.root, 'app', 'views', 'pages', 'info.html.erb')
    info = File.open(info)
    @html_info = Nokogiri::HTML(info, nil, 'utf-8')
    info.close

    archiv = File.join(Rails.root, 'app', 'views', 'pages', 'archiv.html.erb')
    archiv = File.open(archiv)
    @html_archiv = Nokogiri::HTML(archiv, nil, 'utf-8')
    archiv.close

  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Kontakt<% end %>

<section class="contacts">
  <h3>Kontakt</h3>
  <article>
	  <section class="col-sm-6">
      <h4>Zašlete mi zprávu</h4>
      <%= form_for :contact, url: contacts_path do |f| %>
      <div class="form-group">
         <%= f.label :name, "Vaše jméno:" %>

         <%= f.text_field :name, class: "form-control" %>
       </div>
       <div class="form-group">
          <%= f.label :email, "Váš email:" %>
          <%= f.text_field :email, class: "form-control" %>
        </div>

       <div class="form-group">
          <%= f.label :message, "Vaše zpráva:" %>
          <%= f.text_field :message, class: "form-control" %>
        </div>

        <%= f.submit "odeslat", class: "btn btn-default" %>
      <% end %>


    </section>
	  <section class="col-sm-6 contact">
      <h4>Kontaktní informace</h4>
      <div>Máte-li zájem o mé služby či jakýkoli dotaz, neváhejte mne kontaktovat prostřednictvím kontaktního formuláře, či na níže uvedených kontaktech.</div>

      <div>
        <ul>

          <li><strong style="color: #465A7A; font-weight:800;">Slatina 30, 273 26 Slatina, okres Kladno</strong></li>
          <li><a href="http://mapy.cz/s/evxl" style="font-weight:400; color:#7B7B7B; text-decoration:underline">zobrazit na mapě</a></li>
          <li>IČ 45854416, DIČ CZ7155120676</li>
          <li>+420 606 419 246</li>
          <li><%= mail_to "jitka@planska.cz"%></li>
          <li><%= link_to "www.planska.cz", "http://www.planska.cz/"%></li>
          <li><%= link_to "Živnost rejstřík", "http://www.rzp.cz/cgi-bin/aps_cacheWEB.sh?VSS_SERV=ZVWSBJFND&Action=Search&PRESVYBER=0&PODLE=subjekt&ICO=45854416&OBCHJM=&JMENO=&PRIJMENI=&NAROZENI=&ROLE=&OKRES=&OBEC=&CASTOBCE=&ULICE=&COR=&COZ=&CDOM=&VYPIS=1"%></li>
        </ul>
      </div>
    </section>
  </article>
</section>

app/views/layouts/_footer.html.erb
<article>
	<strong>Jitka Plánská</strong> &copy; 2008 - <%= DateTime.now.year %>. Vyrobeno v <a href="http://jedemedobaru.cz/">jedemedobaru.cz</a>, grafika: <strong>Lucie Kepplová</strong>, kód: <strong>Adam Plánský</strong>
</article>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-right">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <%= link_to 'Home', root_path, class: 'navbar-brand' %> -->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav" >
         <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Profil', root_path %></li>
<li><%= link_to 'Nabídka služeb', page_path('services') %></li>
<li><%= link_to 'Ceník', page_path('pricelist')%></li>
<li><%= link_to 'Odkazy', page_path('links')%></li>
<li><%= link_to 'Relax', page_path('relax')%></li>
<li><%= link_to "Kontakt", new_contact_path %></li>

app/views/layouts/_top_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="header">
    <div class="container top_nav col-sm-6">
  	  <ul>
  		  <li><span class="glyphicon glyphicon-earphone"></span>+420 606 419 246</li>
  		  <li><span class="glyphicon glyphicon-envelope"></span>jitka@planska.cz</li>
  	  </ul>
    </div>
    <div class="top_nav pull-right col-sm-6">
      <ul class="right_links">
        <li><%= link_to 'Aktuálně', page_path('actually')%></li>
        <li><%= link_to 'Info', page_path('info')%></li>
        <li><%= link_to 'Archiv', page_path('archiv')%></li>
      </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
	<title><%= content_for?(:title) ? yield(:title) : "www.planska.cz - účetní poradenství" %></title>
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Poskytujeme poradenství, zpracováváme účetnictví, daňovou evidenci, mzdovou agendu, přiznání k daním pro malé a střední firmy." %>">
   <meta name="author" content="Adam Plánský">
   <meta name="robots" content="index,follow"> 
   <meta name="keywords" content="účetnictví, daňová evidence, Kralupy nad Vltavou, Kladno, účetní kancelář">
  <%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  
  
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400,600,700,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  
  
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= render 'layouts/top_navigation' %>
		<%= render 'layouts/navigation' %>
	</header>
	<main role="main">
		<%= render 'layouts/messages' %>
    
    <section id="default" data-type="background">
    	<section class="header-img-inner col-sm-6">
    		<h1>Jitka Plánská</h1><br />
    		<h2>účetnictví, daňová evidence</h2><br />
    		<h2>mzdy, poradenství</h2>
    	</section>
    </section>
    
    
		<%= yield %>
	</main>
	<footer>
		<%= render 'layouts/footer' %>		
	</footer>
  
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57280628-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/pages/2014.html.erb
<% i = -1 %>

<section class="2014 top_nav_content">
  <h1>2014</h1>
  <article>
    
<% i+=1%><h2 id="<%= i %>"><a class="link">Sleva pro důchodce za rok 2013 zpětně přiznána</a></h2>
<div class="content">
<p>Na základě právní analýzy nálezu Ústavního soudu I.ÚS 2340/2013 dospěla finanční správa k závěru, že ustanovení znemožňující uplatnit základní slevu na dani z příjmů pro starobní důchodce nebude za rok 2013 aplikovat. Fyzické osoby dotčené touto skutečností, u kterých sleva na dani doposud nebyla zohledněna, mohou svůj nárok uplatnit podáním řádného (dodatečného) daňového přiznání za zdaňovací období roku 2013. </p>
  <a href="http://www.financnisprava.cz/cs/dane-a-pojistne/dane/dan-z-prijmu/dotazy-a-odpovedi/casto-kladene-dotazy-sleva-na-dani-pro-starobni-duchodce-5391">
    Dotazy a odpovědi k uplatňování slevy na dani pro starobní důchodce
  </a>
</div>
    
    
<% i+=1%><h2 id="<%= i %>"><a class="link">Cestovní náhrady 2014</a></h2>
<div class="content">
    <h3>Základní náhrady 2013/2014</h3>
    <i>(§ 157/4 ZP)</i> <br>
    <ul>
      <li>Za 1 km jízdy 3,60 / 3,70</li>
    </ul>
    <h3>Průměrné ceny PHM 2013/2014</h3>
      
    <i> (§ 158/3 ZP)</i> <br>
    <ul>
      <li>Benzin 95 oktanů 36,10 / 35,70</li>
      <li>Benzin 98 oktanů 38,60 / 37,90</li>
      <li>Nafta 36,50 / 36,00</li>
    </ul>
    <h3>Tuzemské stravné 2013/2014</h3>
    <p><strong>Státní a příspěvková sféra</strong></p>
    <i>(§ 176/1 ZP)</i> <br>
    <ul>
      <li>2013 / 2014</li>
      <li>5 – 12 hod.  66-79 / 67-80</li>
      <li>12-18 hod.  100-121 / 102-123</li>
      <li>nad 18 hod. 157-188 / 160-191</li>
    </ul>
    <p><strong>Podnikatelská sféra</strong></p>
    <i>(§ 163/1 ZP)</i> <br>
    <ul>
      <li>2013/ 2014</li>
      <li>5 – 12 hod. 66 / 67</li>
      <li>12-18 hod. 100 / 102</li>
      <li>nad 18 hod. 157 / 160</li>
    </ul>
</div>

<% i+=1%><h2 id="<%= i %>"><a class="link">Minimální zálohy OSVČ 2014</a></h2>
<div class="content">
    <ul>
      <li><span>Zdravotní </span>1752,-</li>
      <li><span>Sociální  hlavní činnost</span> 1894,-;  <span>vedlejší činnost </span>758,-</li>
      <li><span>Nemocenské </span>115,-  </li>
    </ul>
    <p>Podmínka, která určovala, že OSVČ, která je účastna nemocenského pojištění, nemůže být považována za OSVČ vykonávající vedlejší činnost, přestože trvaly důvody pro vedlejší činnost, je od 1. 1. 2014 zrušena.</p>
</div>

<% i+=1%><h2 id="<%= i %>"><a class="link">Zdanění DPP bez prohlášení 2014</a></h2>
<div class="content">
    <p>Srážková daň u mezd u zaměstnanců s NEPODEPSANÝM PROHLÁŠENÍM:</p>
    <p>2013 / <strong>2014</strong></p>
    <p>Příjem do 5000 za měsíc / Příjem do <strong>10000</strong> za měsíc <strong>POUZE PŘÍJEM Z DPP !!!</strong></p>
    <p><strong>Potvrzení o příjmech  pro poplatníky se srážkovou daní</strong> od 1.1.2014(srážková daň se vztahuje POUZE na příjmy z dohody o provedení práce, při nepodepsaném prohlášení k dani a měsíčním příjmu maximálně 10.000 Kč)</p>
    <p><strong> Zahrne-li poplatník příjmy z DPP do daňového přiznání, započte se daň sražená z těchto příjmů na jeho daň.</strong></p>

</div>

<% i+=1%><h2 id="<%= i %>"><a class="link">POZEMKY A DPH OD 2014</a></h2>
<div class="content">
    <a href="http://www.financnisprava.cz/assets/cs/prilohy/d-placeni-dani/Informace_k_par_56_od_roku_2014.pdf">http://www.financnisprava.cz/assets/cs/prilohy/d-placeni-dani/Informace_k_par_56_od_roku_2014.pdf</a>
    <p>Schválená novela zákona o DPH rozšiřuje rozsah případů, kdy <strong>pozemky nebudou od roku 2014 od DPH při převodu osvobozeny</strong>. Skok může nastat u staveb pro bydlení, a to až <strong>na 21 %</strong>.</p>
    <h3>Příklad 1:</h3>
    <p>Je převáděn pozemek, na který je vydáno stavební povolení na nemovitou stavbu. Na pozemku byla postavena několik měsíců před převodem stavební buňka, která je spojena se zemí napojením na vodu a kanalizaci.</p>
    <p><strong>V roce 2013 </strong>půjde o převod pozemku osvobozený od DPH. Stavebním zdanitelným pozemkem tento pozemek být nemůže, protože je zastavěn stavbou.</p>
    <p><strong>V roce 2014 </strong>půjde o převod pozemku zdanitelný DPH, neboť není splněno kritérium převodu nezastavěného pozemku bez stavebního povolení a od započetí užívání stavby na pozemku neuplynulo více než 5 let.</p>
    <h3>Příklad 2:</h3>
    <p>Je převáděn pozemek, na kterém je nemovitá stavba užívaná a od kolaudace 2 roky. </p>
    <p><strong>V roce 2013 </strong>půjde o převod pozemku osvobozený od DPH. Pozemek je zastavěn stavbou, nemůže proto být pozemkem stavebním.</p>
    <p><strong>V roce 2014 </strong>půjde o převod pozemku zdanitelný DPH, neboť není splněno kritérium převodu nezastavěného pozemku bez stavebního povolení a od započetí užívání stavby na pozemku neuplynulo více než 5 let. Sazba daně bude základní.</p>
    <h3>Příklad 3:</h3>
    <p>Je převáděn pozemek, na kterém je nemovitá stavba pro sociální bydlení užívaná a od kolaudace uplynuly 2 roky. Stavba je vlastněná jinou osobou než pozemek, v lednu 2014 je zřízeno právo stavby a je zapsáno do katastru nemovitých věcí.</p>
    <p><strong>V roce 2013 </strong>půjde o převod pozemku osvobozený od DPH. Pozemek je zastavěn stavbou, nemůže proto být pozemkem stavebním.</p>
    <p><strong>V roce 2014 </strong>půjde o převod pozemku zdanitelný DPH, neboť není splněno kritérium převodu nezastavěného pozemku bez stavebního povolení a od započetí užívání stavby na pozemku neuplynulo více než 5 let. Je otázkou, zda bude možné na převod pozemku aplikovat sníženou sazbu</p>
    <p>(2) Zbožím se pro účely tohoto zákona rozumí od 1.1.2014</p>
    <ol type="a">
      <li>hmotná věc, s výjimkou peněz a cenných papírů,</li>
      <li>právo stavby,</li>
      <li>živé zvíře,</li>
      <li>lidské tělo a část lidského těla,</li>
      <li>plyn, elektřina, teplo a chlad.</li>
    </ol>
</div>  

<% i+=1%><h2 id="<%= i %>"><a class="link">Prodejci tvrdého alkoholu musí mít od 17.10.2013 koncesi</a></h2>
<div class="content">
    <p><i>Novela živnosten. Zákona – příloha č. 3, účinnost od 17.10.2013</i></p>
      <ul>
        <li>Novela se týká kromě<strong> prodejců lihovin v obchodě </strong>také podnikatelů,
          kteří tvrdý alkohol prodávají <strong>v restauracích, cukrárnách, dopravních prostředcích…
          </strong>
        </li>
        <li>Podnikatelé podají na ŽÚ žádost o koncesi s předmětem podnikání „<strong>Prodej
            kvasného lihu, konzumního lihu a lihovinů</strong>“, a to ve stanoveném termínu
            6 měsíců ode dne účinnosti novely, <strong>tedy nejdéle do 16. dubna 2014.</strong>
          </li>
          <li>Koncesi vystaví ŽÚ zdarma. Po půl roce (od 17.4.2014), pokud podnikatel o tuto koncesi
              nepožádá, mu bude pozastavena činnost a bude si muset udělat novou živnost za poplatek.
          </li>
        </ul>
</div>

<% i+=1%><h2 id="<%= i %>"><a class="link">Náhradu mzdy bude zaměstnavatel od ledna vyplácet opět jen po dobu 14 dnů </a></h2>
<div class="content">
<p>
<strong>Od ledna příštího roku budou zaměstnavatelé svému zaměstnanci, který byl uznán
dočasně práce neschopným, vyplácet náhradu mzdy za období prvních 14 kalendářních
dnů trvání pracovní neschopnosti namísto dosavadních 21 dnů.</strong></p>
<p>
Zaměstnanec, který bude uznán práce neschopným nebo mu bude nařízena karanténa až
v roce 2014:
</p>
<ul>
<li>bude mít nárok na nemocenské od okresní správy sociálního zabezpečení již od 15.
dne trvání pracovní neschopnosti či karantény;</li>
<li>v období prvních 14 dnů bude mít nárok na náhradu mzdy od zaměstnavatele; </li>
<li>nadále platí, že zaměstnavatel poskytuje náhradu mzdy za dny, které jsou pro zaměstnance
pracovními dny, a že za první tři pracovní dny (nejvýše však za 24 odpracovaných
hodin) náhrada mzdy nenáleží. Při karanténě náleží náhrada mzdy od prvního pracovního
dne;</li>
<li><strong>pokud bude zaměstnanec uznán práce neschopným nebo mu bude nařízena karanténa
ještě v roce 2013 a pracovní neschopnost či karanténa bude přecházet do roku 2014,
musí zaměstnavatel poskytovat náhradu mzdy postaru, tedy v prvních 21 dnech jejího
trvání</strong> připomíná Koníček. I když zaměstnanec bude uznán práce neschopným
ode dne 31. prosince 2013, bude zaměstnavatel poskytovat náhradu mzdy až do 20.
ledna 2014, pokud pracovní neschopnost zaměstnance bude tak dlouho trvat.</li>
</ul>
<p><a href="files/kolik_penez_za_promarodeny_den.xlsx">kolik peněz za promaroděný den.xlsx</a></p>
</div>




  </article>
</section>

app/views/pages/index.html.erb
<section>
  <h3>VÍTEJTE NA STRÁNKÁCH<br /> ÚČETNÍ PORADKYNĚ JITKY PLÁNSKÉ</h3>
	<article>


		<p>Účetní kancelář byla založena v roce 1995, nabízí proto mnohaleté zkušenosti. Oblast působnosti je především Kladno a Kladensko, Praha, Kralupy nad Vltavou a blízké okolí. Naše služby jsou určeny pro fyzické i právnické osoby.</p>
		<p>Poskytujeme poradenství, zpracováváme účetnictví (dříve podvojné účetnictví), daňovou evidenci (dříve jednoduché účetnictví), mzdovou agendu, přiznání k daním pro malé a střední firmy, zastupujeme klienty na úřadech. Nabízíme komplexní a individuální přístup ke každému klientovi. Dle jeho požadavků a potřeb sjednáváme schůzky v jakoukoliv hodinu, i o víkendech, aby vzájemná spolupráce nijak nenarušovala obchodní činnost společnosti. Naším hlavním cílem je spokojený zákazník, proto za klíčový prvek považujeme komunikaci . Za každých okolností se snažíme porozumět klientovi a přizpůsobit se jeho požadavkům.</p>
	</article>
</section>

<section id="dane">
	<article>
		„Nic není jisté, jen smrt a daně...“
	</article>
</section>



<section id="submenu">
	<article>
		<section class="col-sm-4">
			<section>
				<h4><%= @html_act.css('h1').text %></h4>
				<ul>
					<% @html_act.css('h2').each_with_index do |x, i| %>
            <li><span class="glyphicon glyphicon-chevron-right"></span><a href="/pages/actually#<%= i.to_s %>"><%=x.text %></a></li>
          <% end %>
				</ul>
			</section>
		</section>
		<section class="col-sm-4">
			<section>
				<h4><%= @html_info.css('h1').text %></h4>
				<ul>
					<% @html_info.css('h2').each_with_index do |x, i| %>
            			<li><span class="glyphicon glyphicon-chevron-right"></span><a href="/pages/info#<%= i.to_s %>"><%=x.text %></a></li>
          			<% end %>
				</ul>
			</section>
		</section>
		<section class="col-sm-4">
			<section>
				<h4><%= @html_archiv.css('h1').text %></h4>
			<ul>
				<% @html_archiv.css('h2').each_with_index do |x, i| %>
          <li><span class="glyphicon glyphicon-chevron-right"></span><a href="/pages/archiv#<%= i.to_s %>"><%=x.text %></a></li>
        <% end %>
			</ul>
			</section>
		</section>
	</article>
</section>

app/views/pages/links.html.erb
<% content_for :title do %>Odkazy<% end %>

<section class  = "links">
  <h3>Odkazy</h3>
  <article>
    <div class="col-sm-4 col">

      <div class = "in-header">
        užitečné odkazy
      </div>

      <div class = "body">
        <ul>
         <li><a href="http://wwwinfo.mfcr.cz/ares/">ARES</a></li>
         <li><a href="http://business.center.cz/">Business.center</a></li>
         <li><a href="http://www.businessinfo.cz/cz/rubrika/zmeny-od-roku-2012/1001697/">Business Info</a></li>
         <li><a href="http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.jsp">Denní kurzy  ČNB</a></li>
         <li><a href="http://epodatelna.justice.cz/ePodatelna/epo1200new/form.do">E-podatelna justice</a></li>
         <li><a href="http://www.finance.cz">Finance</a></li>
         <li><a href="http://www.cnb.cz/cs/platebni_styk/iban/iban.html">Kalkulátor IBAN</a></li>
         <li><a href="http://www.nur.cz/">Národní účetní rada</a></li>
         <li><a href="https://or.justice.cz/ias/ui/rejstrik">Obchodní rejstřík</a></li>
         <li> <%= link_to "Pokyn č. D-300 - uplatňování zákona o daních z příjmů", "/files/pokyn_D_300.pdf" %> </li>
         <li> <%= link_to "Pokyn GFŘ č. D-6", "/files/PokynGFRcD6.pdf" %> </li>
         <li><a href="http://adisreg.mfcr.cz/cgi-bin/adis/idph/int_dp_prij.cgi?ZPRAC=FDPHI1&amp;poc_dic=1">Registr českých plátců </a></li>
         <li><a href="http://ec.europa.eu/taxation_customs/vies/vieshome.do?selectedLanguage=EN">Registr plátců z EU </a></li>
         <li> <%= link_to "Struktura DIČ v EU", "/files/struktura_dic.pdf" %> </li>
         <li><a href="http://www.rzp.cz/">Živnostenský rejstřík</a></li>
        </ul>
      </div>

    </div>
    <div class="col-sm-4 col">

      <div class="in-header">
        instituce
      </div>

      <div class = "body">
        <ul>
          <li>Vláda ČR <a href="http://www.vlada.cz/">www.vlada.cz</a></li>
          <li>Ministerstvo financí <a href="http://www.mfcr.cz/cps/rde/xchg/">www.mfcr.cz</a>,
            <a href="http://www.mfcr.cz/cps/rde/xchg/mfcr/hs.xsl/dc2_tiskopisy.html">tiskopisy</a></li>
          <li>Česká správa sociálního zabezpečení <a href="http://www.cssz.cz/cz/novinky/">www.cssz.cz</a>,
            <a href="http://www.cssz.cz/cz/tiskopisy/">tiskopisy</a>
          </li>
          <li>Všeobecná zdravotní pojišťovna <a href="http://www.vzp.cz/cms/internet/cz/">www.vzp.cz</a></li>
        </ul>
      </div>

    </div>
    <div class="col-sm-4 col">

      <div class = "in-header">
        zákony
      </div>

      <div class = "body">
        <ul>
         <li>Sbírka zákonů, poslední 4 týdny <a href="http://www.sbirka.cz/">www.sbirka.cz </a></li>
         <li>Daně a účetnictví (Verlag-Dashöfer) <a href="http://www.du.cz/">www.du.cz</a></li>
         <li>Sagit (nakladatelství) <a href="http://www.sagit.cz/">www.sagit.cz</a></li>
         <li>Účetní svět <a href="http://www.ucetnisvet.cz/">www.ucetnisvet.cz </a></li>
         <li>Tiskopisy <a href="http://www.form.cz/">www.form.cz</a></li>
        </ul>
      </div>
    </div>







</article>


</section>

app/views/pages/pricelist.html.erb
<% content_for :title do %>Ceník<% end %>

<section class="pricelist">
  <h3>Ceník</h3>
  <article>

    <p>Uvedené ceny jsou pouze orientační. Mohou se měnit jak směrem nahoru, tak i směrem dolů podle množství účetních případů a kvality dodaných podkladů. Veškeré ceny prací lze individuálně přizpůsobit v závislosti na mnoha faktorech. Díky nízkým režijním nákladům můžeme nabídnout opravdu nízké ceny na trhu při zachování vysoké kvality.</p>

    <p>Stálým klientům není účtováno přiznání k DPH a k silniční dani.</p>


    <table>
      <tr>
        <th colspan="2">
          Orientační ceník
        </th>
      </tr>
      <tr><td colspan="2">Vedení daňové evidence</td></tr>
      <tr><td>Převzetí daňové evidence</td><td>od 700,- Kč</td></tr>
      <tr><td>Položka v účetním deníku</td><td>od 17,- Kč</td></tr>
      <tr><td  colspan="2">Vedení účetnictví</td></tr>
      <tr><td>Převzetí účetnictví</td><td>od 1800,- Kč</td></tr>
      <tr><td>Položka v účetním deníku</td><td>od 23,- Kč</td></tr>
      <tr><td  colspan="2">Vedení mezd</td></tr>
      <tr><td>Zpracování mzdy</td><td>od 300,- Kč / osoba / měsíc</td></tr>
      <tr><td  colspan="2">Konzultace</td></tr>
      <tr><td>Hodinová sazba</td><td>od 500,- Kč </td></tr>
    </table>

  </article>
</section>